### ISSUE TITLE
点击 coin_btn 对象时，uiautomator2 抛出了一个 RPCUnknownError 异常

### ISSUE THREAD

**Issue by ERRORFailed** [czl0325/coin11-tb#3]
>python 淘宝双11.py
检查弹窗开始
检查弹窗结束
Traceback (most recent call last):
  File "I:\123\coin11-tb-main\淘宝双11.py", line 71, in <module>
    d.click(coin_btn[0].center()[0], coin_btn[0].center()[1])
  File "I:\Program Files (x86)\python\Lib\site-packages\uiautomator2\__init__.py", line 403, in click
    self.jsonrpc.click(x, y)
  File "I:\Program Files (x86)\python\Lib\site-packages\uiautomator2\__init__.py", line 185, in __call__
    return self.server.jsonrpc_call(self.method, params, http_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Program Files (x86)\python\Lib\site-packages\uiautomator2\core.py", line 270, in jsonrpc_call
    return _jsonrpc_call(self._dev, method, params, timeout, self._debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Program Files (x86)\python\Lib\site-packages\uiautomator2\core.py", line 153, in _jsonrpc_call
    raise RPCUnknownError(f"Unknown RPC error: {code} {message}", params, stacktrace)
uiautomator2.exceptions.RPCUnknownError: ('Unknown RPC error: -32001 java.lang.SecurityException', (489.0, 417.0), 'java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission\n\tat android.os.Parcel.createException(Parcel.java:2074)\n\tat android.os.Parcel.readException(Parcel.java:2042)\n\tat android.os.Parcel.readException(Parcel.java:1990)\n\tat android.view.IWindowManager$Stub$Proxy.injectInputAfterTransactionsApplied(IWindowManager.java:5020)\n\tat android.app.UiAutomationConnection.injectInputEvent(UiAutomationConnection.java:131)\n\tat android.app.UiAutomation.injectInputEvent(UiAutomation.java:597)\n\tat com.wetest.uia2.stub.TouchController.injectEventSync(TouchController.java:38)\n\tat com.wetest.uia2.stub.TouchController.touchDown(TouchController.java:47)\n\tat com.wetest.uia2.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:191)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)\n\tat com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)\n\tat com.wetest.uia2.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:101)\n\tat fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)\n\tat fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)\n\tat fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)\n\tat java.lang.Thread.run(Thread.java:919)\nCaused by: android.os.RemoteException: Remote stack trace:\n\tat com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:733)\n\tat com.android.server.input.InputManagerService.access$1600(InputManagerService.java:125)\n\tat com.android.server.input.InputManagerService$LocalService.injectInputEvent(InputManagerService.java:2459)\n\tat com.android.server.wm.WindowManagerService.injectInputAfterTransactionsApplied(WindowManagerService.java:8311)\n\tat android.view.IWindowManager$Stub.onTransact(IWindowManager.java:2412)\n\n')

从你提供的错误信息来看，问题出在尝试点击 coin_btn 对象时，uiautomator2 抛出了一个 RPCUnknownError 异常。这个异常是由于 java.lang.SecurityException 引起的，具体的错误信息是：

java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
这意味着你的脚本在尝试向另一个应用注入事件（如点击事件）时，没有获得必要的权限。在Android系统中，INJECT_EVENTS 权限是一个签名权限，通常只有系统应用或者具有系统权限的应用才能获得。

要解决这个问题，你可以尝试以下几种方法：

确保应用具有权限：如果你是在开发一个应用，确保你的应用具有 android.permission.INJECT_EVENTS 权限。这通常需要在应用的 AndroidManifest.xml 文件中声明。

使用具有权限的应用：如果你是在进行自动化测试，确保你使用的自动化测试工具（如 uiautomator2）具有足够的权限。

调整设备设置：在某些情况下，你可能需要调整设备的设置，以允许你的应用注入事件。这可能涉及到开发者选项中的某些设置。

使用其他方法模拟点击：如果上述方法都不可行，你可以考虑使用其他方法来模拟点击事件，比如使用 adb shell 命令。

检查uiautomator2配置：确保你的 uiautomator2 配置正确，并且与你的设备和应用兼容。

检查设备API级别：不同的Android版本可能有不同的权限要求，确保你的代码与你测试的设备API级别兼容。

如果你不是应用的开发者，而是在使用第三方应用进行自动化测试，那么你可能需要联系应用的开发者，以确保应用具有正确的权限设置。如果你是开发者，那么你需要检查你的应用权限设置，并确保在测试环境中正确配置了这些权限。

**Comment by czl0325** [comment]
开发者选项打开usb调试，允许模拟点击

**Comment by ERRORFailed** [comment]
> 开发者允许选项打开usb调试，点击模拟

强呀兄弟，已经可以了
